import React, { useState, useEffect } from "react";
import { useHistory } from "react-router-dom";
import useWindowSize from "../../../../utils/useWindowSize";

function IntroDashBoard() {
  let history = useHistory();
  const size = useWindowSize();

  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    if (size.width <= 768) setIsMobile(true);
    else setIsMobile(false);
  }, [size]);

  return (
    <div className="bg-[#10213f]">
      <div className="relative w-full h-[100vh] bg-[#000]">
        <div className="invisible md:visible md:pt-[26vh] md:mx-[14.61%] md:text-[24px] text-[#FFFFFF] md:leading-[29px] md:font-[400]">
          Get in the Banking Revolution with
        </div>
        <div className="mt-[30vh] h-[12vh] md:w-full md:h-[30vh] flex items-center justify-center md:mt-[22px]">
          <div className="h-[12vh] bg-introdashboard-logoimage bg-contain bg-center bg-no-repeat w-[653px] md:h-[30vh]"></div>
        </div>
        <div className="absolute bottom-[9vh] w-full md:h-[104px] flex items-center justify-center">
          <div className="md:w-[653px] md:h-[100%] flex flex-col md:flex-row items-center">
            <div className="flex justify-center items-center w-[169px] pb-[16px] md:pb-0 md:w-[284px] md:h-[72px] md:mr-[37px] text-[#FFF] text-[14px] md:text-[24px] leading-[16px] md:leading-[29px] md:font-[500] border-b-[1px] md:border-[1px] border-[#F6F8FA]">
              {isMobile ? "Welcome to Maui" : "Start your journey"}
            </div>
            <div className="md:w-0 md:h-[104px] border-l-[1px] border-[#FFF]"></div>
            <div className="flex justify-between mt-[20px] md:mt-0 md:ml-[37px] w-[160px] md:w-[257px] md:h-[56px]">
              <div className="flex items-center text-[14px] md:text-[24px] md:font-[400] text-[#FFF]">
                {isMobile ? "Watch Fullscreen" : "Watch the Film"}
              </div>
              <div className="w-[31.5px] h-[31.5px] md:w-[56px] md:h-[56px] bg-introdashboard-fullscreenimage bg-cover bg-center"></div>
            </div>
          </div>
        </div>
      </div>
      <div className="relative w-full md:leading-[116px]">
        <div className="absolute left-[29px] top-[87px] right-[190px] bottom-[16px] bg-introdashboard-starimage bg-cover bg-center"></div>
        <div className="pt-[14vh] md:pt-[30vh] px-[20px] md:px-0 text-[45px] md:text-[96px] drop-shadow-[0_4px_17px_rgba(0,0,0,0.58)] text-[#1199FA] md:font-[600] text-left md:text-center">
          <span>Welcome to MAUI, you are</span>
          {!isMobile && <br />}
          <span>now the bank.</span>
          {!isMobile && <br />}
          <span> Banking </span>
          <span className="text-[#FFF]">Reinvented.</span>
        </div>
        <div
          className="md:mt-[20px] md:w-[800px] px-[20px] md:px-0 md:pb-[85px] text-[#FFF] text-left md:text-justify text-[18px] md:text-[24px] md:leading-[29px] font-[400] md:font-[500] md:mx-auto"
          style={{ textAlignLast: isMobile ? "left" : "center" }}
        >
          Banking accesible for everyone on the planet, from institutional money
          looking for higher yields to those unbanked in developing countries.
          With Maui you are the bank.
        </div>
        {isMobile && (
          <div className="px-[20px] mt-[20px] text-[#1199FA] text-[18px] font-[400]">
            With Maui you are the bank
          </div>
        )}
      </div>
      <div className="w-full md:pt-[20vh]">
        <div className="text-[#1199FA] md:text-[74px] md:leading-[78px] md:font-[500] md:text-center">
          Earn
        </div>
        <div className="md:w-[50%] md:mt-[20px] md:mx-auto md:text-[20px] md:leading-[24px] text-[#FFF] md:font-[500] text-center">
          Make a deposit in any currency from anywhere in the world, now you are
          earning 8% fixed rate p.a. on your deposit. You can access it anytime.
        </div>
        <div className="md:w-[30%] md:mt-[110px] md:mx-auto border-b-[7px] border-[#1199FA] h-0 text-center"></div>
        <div className="text-[#1199FA] md:mt-[80px] md:text-[74px] md:leading-[78px] md:font-[500] md:text-center">
          Borrow
        </div>
        <div className="md:w-[50%] md:mt-[20px] md:mx-auto md:text-[20px] md:leading-[24px] text-[#FFF] md:font-[500] text-center">
          Maui Banking revolutionary services come when you borrow. No
          applications, no forms, no risk management. It’s your money, you are
          the bank. No repayments. The loan repays itself with the yields
          generated by your collateral.
        </div>
        <div className="md:mt-[280px] md:mx-auto md:w-[60%] md:text-center md:text-[64px] md:leading-[76px] text-[#FFF] md:font-[500] md:drop-shadow-[0_0_2px_#FFFFFF]">
          <span>Built by MAUI.</span>
          <br /> <span>Banking Revolution is here.</span>
        </div>
        <div className="md:mt-[63px] md:mx-auto md:w-[300px] md:h-[99px] bg-introdashboard-iphonecut bg-cover bg-center"></div>
        <div className="flex items-center md:mt-[50vh] md:mx-auto bg-introdashboard-earn-back bg-contain bg-no-repeat bg-center md:w-[80%] md:h-[35vh]">
          <div className="md:mx-auto md:w-[90%] text-[#FFF] md:text-[64px] text-center md:leading-[76px] md:font-[500] md:drop-shadow-[0_4px_4px_rgba(0,0,0,0.25)]">
            <span>Earn</span> <span className="text-[#1199FA]">8%</span>{" "}
            <span>fixed p.a on your Deposit Withdrawl Anytime.</span>
          </div>
        </div>
        <div className="md:mt-[20px] md:mx-auto md:w-[70%] flex flex-row justify-between">
          <div className="md:w-[50%]">
            <div className="md:mt-[16vh] md:text-[48px] md:leading-[57px] md;font-[600] text-[#1199FA]">
              Earn 8% p.a. Fixed Interest with No Fees
            </div>
            <div className="md:mt-[15px] text-[#FFF] md:text-[16px]">
              {" "}
              Since you are your own bank, you make money from your deposits and
              from your borrowing. No fees/No annual, foreign-transaction, or
              late fees. No financial institution will be able to mach 8% APY
              per year on your deposit.
            </div>
            <div className="flex flex-row items-center justify-between md:mt-[40px] md:w-[253px] text-[#FFF] bg-[#1199FA] rounded-[2px] p-[15px]">
              <div>Calculate Reward</div>
              <div className="bg-introdashboard-arrow bg-cover bg-center md:w-[49px] md:h-[15px]"></div>
            </div>
          </div>
          <div className="md:w-[calc(80vh*334/675)] md:h-[80vh] bg-introdashboard-fullphone bg-cover bg-center"></div>
        </div>
        <div className="bg-introdashboard-linegroup bg-cover bg-center md:w-[100vw] md:h-[calc(100vw*313/1512)]"></div>
        <div className="flex items-center md:mt-[90px] md:mx-auto bg-introdashboard-borrow-back bg-contain bg-no-repeat bg-center md:w-[80%] md:h-[25vh]">
          <div className="md:w-[70%] md:mx-auto md:text-[64px] md:leading-[76px] md:font-[600] text-[#FFF] text-center drop-shadow-[0px_0px_2px_#FFFFFF]">
            Borrow up to 50% of your deposit. Loan pays itself.
          </div>
        </div>
        <div className="md:mt-[100px] mx-auto md:w-[70%] text-[#ffffffeb] md:text-center md:text-[20px] md:leading-[24px] md:font-[500]">
          Welcome to the future of banking, where you are the bank. A system
          designed to serve you, and not the other way around. Let's say you
          deposit $10,000, you then can borrow $5,000 on your deposit instantly
          and not only you don't have to pay interest, but you get pay zero
          money per month. Your collateral gets locked, and the yield generated
          pays off your loan. You have to re imagine the way you see finance.
          Maui brings you the future of people's new way of banking where
          everyone os their own bank and profit from themselves.
        </div>
        <div className="md:pt-[35vh] md:pb-[20vh] md:w-full">
          <div className="relative md:w-[70%] md:mx-auto md:h-[80vh] flex items-center">
            <div className="md:absolute right-0 top-0 md:w-[calc(80vh*643/679)] md:h-[80vh] bg-introdashboard-iPhone-2 bg-cover bg-center"></div>
            <div className="md:w-[55%]">
              <div className="md:text-[45px] md:leading-[54px] text-[#1199FA] md:font-[600]">
                BORROW up to 50% of your deposit instantly and permissionless.
                No repayments.
              </div>
              <div className="md:mt-[10px] text-[#FFF]">
                Maui Banking revolutionary services come when you borrow. No
                applications, no forms, no risk management. It’s your money, you
                are the bank.
              </div>
              <div className="md:mt-[6px] text-[#FFF]">
                No repayments. The loan repays itself with the yields generated
                by your collateral.{" "}
              </div>
              <div className="md:mt-[15px] md:text-[20px] md:leading-[24px] md:font-[500] text-[#FFF] border-[1px] border-[#FFF] md:w-[252px] md:h-[52px] flex items-center justify-center">
                Calculate your Credit
              </div>
            </div>
          </div>
        </div>
        <div className="flex items-center justify-center bg-introdashboard-phone-photo bg-cover bg-center md:w-[100vw] md:h-[calc(100vw*1154/1512)]">
          <div className="md:w-[45%] md:mx-auto text-[#FFF] md:text-[64px] md:leading-[110px] md:font-[600] drop-shadow-[0_4px_26px_rgba(0,0,0,0.25)]">
            <div className="md:text-center">Hello MAUI.</div>
            <div className="md:text-center">
              E-Card or titanium. Your choice
            </div>
          </div>
        </div>
        <div className="md:mt-[30vh] md:w-full flex justify-center md:text-[72px] text-[#1199FA] md:font-[600] capitalize md:leading-[120%]">
          <div className="md:border-b-[5px] border-[#1199FA]">
            Choose Your Maui Card
          </div>
        </div>
        <div className="text-[#FFF] md:w-[75%] md:mt-[60px] md:mx-auto md:text-center md:text-[20px] md:leading-[24px] md:font-[500]">
          Be one of the first cardholders of our titanium card and make history.
          Make deposits and receive 8% per year yield, that's a better return
          than most Hedge Funds and Superannuations across the globe. Borrow up
          to 50% of your collateral instantly. You could even compound it to
          your deposits to increase your yields. That's the future of banking.
        </div>
        <div className="md:mt-[100px] md:mx-auto md:w-[60vw] md:h-[calc(60vw*537/912)] bg-introdashboard-card bg-center bg-cover"></div>
        <div className="md:mt-[75px] md:w-[full] flex justify-center">
          <div className="mx-auto text-[#FFF] md:px-[9.5px] md:py-[14px] md:text-[20px] md:leading-[24px] md:font-[600] border-[2px] border-[#FFF] rounded-[4px]">
            Swipe For Your Card
          </div>
        </div>
        <div className="relative md:mt-[50vh] md:mx-auto md:w-[70%] md:h-[60vh]">
          <div className="md:text-[80px] md:leading-[116px] md:font-[600] text-[#FFF]">
            Be part of Maui Banking Revolution.
          </div>
          <div className="md:w-[45%] md:mt-[20px] text-[#FFF] md:text-[20px] md:leading-[24px] md:font-[400]">
            Get access to unmatched high yields on your money impossible for
            your legacy bank. A new banking system to serve YOU.*
          </div>
          <div className="md:mt-[30px] flex justify-start">
            <div className="bg-[#FFF] text-[#000] md:py-[9px] md:px-[34px] rounded-[20px] md:text-[24px] md:leading-[29px] md:font-[500]">
              Start Now
            </div>
          </div>
          <div className="md:absolute md:bottom-0 md:right-0 md:w-[33vw] md:h-[calc(33vw*443/577)] bg-introdashboard-maccom bg-cover bg-center"></div>
        </div>
        <div className="md:w-full md:h-[30vh]"></div>
      </div>
    </div>
  );
}

export default IntroDashBoard;
